/** FIFA 3-letter codes → ISO 3166-1 alpha-2 for flagcdn fallback */
export const FIFA_TO_ISO2 = {
  ALG: "dz",
  ARG: "ar",
  AUS: "au",
  AUT: "at",
  BEL: "be",
  BRA: "br",
  CAN: "ca",
  CHI: "cl",
  COL: "co",
  CPV: "cv",
  CRO: "hr",
  CIV: "ci",
  CZE: "cz",
  DEN: "dk",
  ECU: "ec",
  EGY: "eg",
  ENG: "gb-eng",
  ESP: "es",
  FRA: "fr",
  GER: "de",
  GHA: "gh",
  IRN: "ir",
  ITA: "it",
  JOR: "jo",
  JPN: "jp",
  KOR: "kr",
  KSA: "sa",
  MAR: "ma",
  MEX: "mx",
  NED: "nl",
  NOR: "no",
  NZL: "nz",
  PAR: "py",
  POR: "pt",
  QAT: "qa",
  RSA: "za",
  SEN: "sn",
  SUI: "ch",
  TUN: "tn",
  URU: "uy",
  USA: "us",
  UZB: "uz",
  WAL: "gb-wls",
};

export function fifaCodeToIso2(code) {
  return FIFA_TO_ISO2[code?.toUpperCase()] || null;
}
